---
- name: Cluster stage 2- global updates
  hosts: all
  become: true

  tasks:
    - name: Update apt
      ansible.builtin.apt:
        update_cache: true
    - name: Upgrade apt
      ansible.builtin.apt:
        upgrade: "full"
    - name: Disable password ssh authentication via regex
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
    - name: Restart ssh service
      ansible.builtin.service:
        name: sshd
        state: restarted
    - name: Install python3
      ansible.builtin.apt:
        name: python3
        state: present
    - name: Install python3-pip
      ansible.builtin.apt:
        name: python3-pip
        state: present
    - name: Install passlib with apt
      ansible.builtin.apt:
        name: python3-passlib
        state: present
    - name: Create ansible user in sudoers
      ansible.builtin.user:
        name: ansible
        shell: /bin/bash
        password: "{{ 'password' | password_hash('sha512') }}"
        groups: sudo
        append: true
        state: present
    - name: Create nodebotanist user in sudoers
      ansible.builtin.user:
        name: nodebotanist
        shell: /bin/bash
        password: "{{ 'password' | password_hash('sha512') }}"
        groups: sudo
        append: true
        state: present
    - name: Copy ssh keys to new user ansible
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/pi/.ssh/id_rsa.pub') }}"
    - name: Copy ssh keys to new user nodebotanist
      ansible.posix.authorized_key:
        user: nodebotanist
        state: present
        key: "{{ lookup('file', '/home/pi/.ssh/id_rsa.pub') }}"
...
