---

- name: Phase 3 -- Install Docker
  hosts: docker
  become: true

  tasks:
    - name: "Install ca-certificates gnupg curl"
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - gnupg
          - curl
        state: present
    - name: "Install docker.io package"
      ansible.builtin.apt:
        pkg: docker.io
        state: present
    - name: "Add nodebotanist to docker user groups"
      ansible.builtin.user:
        name: nodebotanist
        groups: docker
        append: true
    - name: "Add ansible to docker user group"
      ansible.builtin.user:
        name: ansible
        groups: docker
        append: true
...
